In [1]:
import numpy as np

### 1. Data types

In [2]:
num = 365

In [21]:
np_num16 = np.int16(365)
np_num32 = np.int32(365)
np_num64 = np.int64(365)

In [4]:
num, np_num16, np_num32, np_num64

(365, 365, 365, 365)

In [5]:
type(num),type(np_num16),type(np_num32),type(np_num64)

(int, numpy.int16, numpy.int32, numpy.int64)

In [22]:
np_num16.size, np_num32.size, np_num64.size

(1, 1, 1)

**The difference is the space used by these variables in the memory and hence the range of values**

In [61]:
import sys
sys.getsizeof(np_num16.size), sys.getsizeof(np_num32.size), sys.getsizeof(np_num64.size)

(28, 28, 28)

In [73]:
np_num16_1 = np.int16(32768)
np_num16_2 = np.int16(3276812)
np_num16_3 = np.int16(327681234)

In [74]:
np_num16_1, np_num16_2, np_num16_3

(-32768, 12, 1234)

In [75]:
sys.getsizeof(np_num16_1), sys.getsizeof(np_num16_2), sys.getsizeof(np_num16_3)

(26, 26, 26)

It seems the int16 has the limit of 32767 to -32768. For the numbers larger than these there is some kind of circular  bit over writing.

In [76]:
np_num16_array = np.int16([32767,32768])

In [77]:
np_num16_array.sum()

-1

In [78]:
np_num16_array = np.int16([32767,32768,32768*2])

In [80]:
np_num16_array

array([ 32767, -32768,      0], dtype=int16)

In [79]:
np_num16_array.sum()

-1

In [44]:
# This should give an error
np_num16 = np.int16([9223372036854775808, -9223372036854775808])

OverflowError: Python int too large to convert to C long

In [54]:
# This should give an error
np_num32 = np.int32([9223372036854775808, -9223372036854775808])

OverflowError: Python int too large to convert to C long

In [57]:
np_num32 = np.int32([2147483648, -214748364])

In [81]:
np_num32

array([-2147483648,         -10], dtype=int32)

In [46]:
# This should give an error
np_num64 = np.int64([9223372036854775808, -9223372036854775808])

OverflowError: Python int too large to convert to C long

**Bottomline is choose the int (or float) subtype carefully**

### 2. Arrays 

In [83]:
# Array of zeros
zeros_i = np.zeros(5, dtype="i")
zeros_f = np.zeros(5, dtype="f")
zeros_i, zeros_f

(array([0, 0, 0, 0, 0], dtype=int32),
 array([0., 0., 0., 0., 0.], dtype=float32))

So the default is 32 bit.

In [94]:
# Array of random numbers
rand = np.random.rand(5)
rand_int = np.random.randint(low=50, high=100, size=10)
rand, rand_int

(array([0.09149598, 0.45350833, 0.66270366, 0.03760517, 0.14806898]),
 array([65, 95, 87, 54, 97, 87, 79, 62, 57, 66]))

In [99]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [100]:
np.arange(4,10)

array([4, 5, 6, 7, 8, 9])

In [102]:
# Start, Stop, Step
np.arange(4,10,2)

array([4, 6, 8])

In [106]:
# Start, Stop, Step, Type
np.arange(4,10,.5,dtype='f')

array([4. , 4.5, 5. , 5.5, 6. , 6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5],
      dtype=float32)

In [110]:
np.array([1,2,3])

array([1, 2, 3])

In [114]:
np.array([1, 2, 3.0])

array([1., 2., 3.])

** ndarray vs matrix**

In [122]:
np_array = np.array([[1,2,3],[4,5,6]])
np_array

array([[1, 2, 3],
       [4, 5, 6]])

In [123]:
np_mat = np.mat([[1,2,3],[4,5,6]])
np_mat

matrix([[1, 2, 3],
        [4, 5, 6]])

In [124]:
type(np_array), type(np_mat)

(numpy.ndarray, numpy.matrixlib.defmatrix.matrix)

In [125]:
np_array.shape, np_mat.shape

((2, 3), (2, 3))